GET http://localhost:3001/todos/?priority=HIGH&status=IN%20PROGRESS;
###
GET http://localhost:3001/todos/?priority=HIGH;
###
GET http://localhost:3001/todos/?status=TO%20DO;
###
GET http://localhost:3001/todos/?search_q=Play;
###
GET http://localhost:3001/todos/1;
###
PUT  http://localhost:3001/todos/1;
###
POST http://localhost:3001/todos/
###
DELETE  http://localhost:3001/todos/1;





